# -*- coding: utf-8 -*-
"""tokenizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eLMGQzk-NaFra5YyXwuzo3t1M2iVoix
"""

!pip install sentencepiece

from google.colab import drive
drive.mount('/content/drive')

from sys import prefix
import sentencepiece as spm

spm.SentencePieceTrainer.Train(
    input='/content/drive/MyDrive/github/cls-vs-mean-pooling-transformer-classification/data/processed/train.csv',
    model_prefix = '/content/drive/MyDrive/github/cls-vs-mean-pooling-transformer-classification/data/processed/tokenizer',
    vocab_size = 8000,
    model_type='unigram',
    user_defined_symbols=['[CLS]', '[SEP]'],
    pad_id=0, unk_id=1, bos_id=2, eos_id=3
)

